version: "3"

networks:

    khyber:

        external: false

        driver: bridge

volumes:

    timescaledb:

        external: false

services:

    timescaledb:

        restart: unless-stopped

        networks:
            - khyber

        # ports:
            # - "5432:5432"

        container_name: timescaledb

        volumes:
            - "timescaledb:/var/lib/postgresql/data"

        image: timescale/timescaledb:2.5.1-pg13

        env_file:
            - timescaledb.env

    flyway:

        restart: on-failure

        networks:
            - khyber

        container_name: flyway

        command: migrate

        volumes:
            - "./flyway/sql:/flyway/sql"
            - "./flyway/conf:/flyway/conf"

        image: flyway/flyway:8.4.4-alpine

        depends_on:
            - timescaledb
