version: "3"

networks:

    khyber:

        external: false

        driver: bridge

volumes:

    timescaledb:

        external: false

services:

    timescaledb:

        restart: unless-stopped

        networks:
            - khyber

        # ports:
            # - "5432:5432"

        container_name: timescaledb

        volumes:
            - "timescaledb:/var/lib/postgresql/data"

        image: timescale/timescaledb:2.5.1-pg13

        env_file:
            - timescaledb.env

    traccar:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "8082:8082"
            - "5055:5055"
            - "5179:5179"

        container_name: traccar

        volumes:
            - ./traccar.xml:/opt/traccar/conf/traccar.xml

        image: irasus/traccar:22.02

        # build: .

        depends_on:
            - timescaledb
